// Generated by gir (https://github.com/gtk-rs/gir @ 85fe8474df07)
// from  (@ 683afa56fee3+)
// from gir-files (@ b87d34dc3455)
// DO NOT EDIT

#[cfg(not(docsrs))]
use std::process;

#[cfg(docsrs)]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(docsrs))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        process::exit(1);
    }
}
