// Generated by gir (https://github.com/gtk-rs/gir @ 7f2812366622)
// from  (@ 9fd945b7de58+)
// from gir-files (@ 6cef10cd64df)
// DO NOT EDIT

fn main() {
    if std::env::var("DOCS_RS").is_ok() {
        // prevent linking libraries to avoid documentation failure
        return;
    }

    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        std::process::exit(1);
    }
}
