variables:
  # Clone test-images
  GIT_SUBMODULE_STRATEGY: recursive
  RUST_BACKTRACE: "full"

.install_dependencies:
  before_script:
    - apt update
    - apt install -y git curl meson pkg-config build-essential liblcms2-dev gettext clang mold bubblewrap libseccomp-dev
    # libdrm-dev libheif-dev libgtk-4-dev

    #- git clone --depth 1 https://gitlab.freedesktop.org/cairo/cairo.git
    #- meson setup cairo/builddir cairo
    #- ninja install -C cairo/builddir
    #- git clone --depth 1 https://gitlab.gnome.org/GNOME/gtk.git
    #- meson setup -Dmedia-gstreamer=disabled -Dbuild-testsuite=false -Dbuild-examples=false -Dbuild-tests=false gtk/builddir gtk
    #- ninja install -C gtk/builddir

    - echo "deb https://deb.debian.org/debian/ testing main" >> /etc/apt/sources.list
    - apt update
    - apt install -y libheif-dev libgtk-4-dev libcairo2-dev

    - echo "deb https://deb.debian.org/debian/ unstable main" >> /etc/apt/sources.list
    - echo "deb https://deb.debian.org/debian/ experimental main" >> /etc/apt/sources.list
    - apt update
    - apt install libjxl-dev -t experimental -y

    - fc-cache
  artifacts:
    when: always
    paths:
      - tests/failures
      - builddir/meson-logs

x86_64:
  image: rust:1.75-bookworm
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/
    # Skip isolated install for tests to test usual installation scenario
    - meson setup -Dprofile=dev -Dtest_skip_install=true builddir
    - meson install -C builddir
    - meson test -vC builddir

i386:
  # Use hash to force i386, lookup here <https://hub.docker.com/r/i386/rust/tags>
  image: rust@sha256:ade85905b82458a399a2d86bfaebf666e33ed8d70f55328ede3190f313f5957f
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/i386-linux-gnu/
    - meson setup -Dprofile=dev -Dtest_skip_install=true builddir
    - meson install -C builddir
    - meson test -vC builddir

aarch64:
  image: rust:1.75-bookworm
  tags:
    - aarch64
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu/
    - meson setup -Dprofile=dev -Dtest_skip_install=true builddir
    - meson install -C builddir
    - meson test -vC builddir

cargo-deny:
  interruptible: true
  image: rust
  script:
    - cargo install cargo-deny
    - cargo deny check
