variables:
  # Clone test-images
  GIT_SUBMODULE_STRATEGY: recursive
  RUST_BACKTRACE: "full"

.install_dependencies:
  before_script:
    - apt update
    - apt install -y git curl meson pkg-config build-essential liblcms2-dev gettext clang mold bubblewrap
    # libdrm-dev libheif-dev libgtk-4-dev

    #- git clone --depth 1 https://gitlab.freedesktop.org/cairo/cairo.git
    #- meson setup cairo/builddir cairo
    #- ninja install -C cairo/builddir
    #- git clone --depth 1 https://gitlab.gnome.org/GNOME/gtk.git
    #- meson setup -Dmedia-gstreamer=disabled -Dbuild-testsuite=false -Dbuild-examples=false -Dbuild-tests=false gtk/builddir gtk
    #- ninja install -C gtk/builddir

    - echo "deb https://deb.debian.org/debian/ testing main" >> /etc/apt/sources.list
    - apt update
    - apt install -y libheif-dev libgtk-4-dev libcairo2-dev
  artifacts:
    when: always
    paths:
      - tests/failures
      - builddir/meson-logs
i386:
  image: rust@sha256:05126659e6a1ddfd54def494bd485bb50b19446f61c92cb1c6559aa6cfecd922
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/i386-linux-gnu/
    - meson setup -Dprofile=dev builddir
    - meson test -vC builddir

x86_64:
  image: rust:bookworm
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/
    - meson setup -Dprofile=dev builddir
    - meson test -vC builddir

cargo-deny:
  interruptible: true
  image: rust
  script:
    - cargo install cargo-deny
    - cargo deny check
