variables:
  # Clone test-images
  GIT_SUBMODULE_STRATEGY: recursive
  RUST_BACKTRACE: "full"
  TARBALL_ARTIFACT_PATH: "builddir/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

.cargo_bininstall:
  before_script:
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

.install_dependencies:
  before_script:
    - whoami
    - apt-get update
    - apt-get install -y git curl meson pkg-config gobject-introspection gi-docgen valac libgirepository1.0-dev python3-gi build-essential gettext clang mold bubblewrap libseccomp-dev libfontconfig-dev
    - apt-get install -y libgtk-4-dev libcairo2-dev librsvg2-2 libjxl-dev
    # We need libfheif 1.20
    - echo "deb http://deb.debian.org/debian forky main" > /etc/apt/sources.list.d/forky.list
    - apt-get update
    - apt-get install -y libheif-dev libheif-plugin-aomenc libheif-plugin-x265

  artifacts:
    when: always
    paths:
      - tests/failures
      - builddir/meson-logs

test-aarch64:
  image: rust:1.93-trixie
  tags:
    - flatpak-aarch64
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu/
    - meson setup -Dprofile=dev -Dpython_tests=true -Dtest_skip_install=true --prefix=/usr -Dloaders=glycin-heif,glycin-image-rs,glycin-jxl,glycin-raw,glycin-svg,glycin-test builddir
    - meson install -C builddir
    - meson test -vC builddir
