include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "build-release-tarball"              # <1.>
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"   # <2.>

variables:
  # Clone test-images
  GIT_SUBMODULE_STRATEGY: recursive
  RUST_BACKTRACE: "full"
  TARBALL_ARTIFACT_PATH: "builddir/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"


.install_dependencies:
  before_script:
    - apt update
    - apt install -y git curl meson pkg-config gobject-introspection gi-docgen valac libgirepository1.0-dev python3-gi build-essential liblcms2-dev gettext clang mold bubblewrap libseccomp-dev libfontconfig-dev

    #- git clone https://github.com/libjxl/libjxl.git --recursive --shallow-submodules
    #- apt-get install -y clang cmake pkg-config libbrotli-dev
    #- export CC=clang CXX=clang++
    #- cd libjxl
    #- mkdir build
    #- cd build
    #- cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF ..
    #- cmake --build . -- -j$(nproc)
    #- cmake --install .
    #- cd ../..

    - echo "deb https://deb.debian.org/debian/ testing main" >> /etc/apt/sources.list
    - apt-get update
    - apt-get install -y libheif-dev libgtk-4-dev libcairo2-dev meson
    - apt-get install -y librsvg2-2
    - apt-get install -y libjxl-dev
    # Fix valac issue in bookworm
    - apt-get install -y valac
    # Get QOI support in bookworm
    - apt-get install -y shared-mime-info
    # Required for librsvg/fontconfig, somehow fails to install automatically.
    # Issue is new, first seen 2024-09-12
    - apt-get install -y libbz2-dev
  artifacts:
    when: always
    paths:
      - tests/failures
      - builddir/meson-logs

build-release-tarball:
  stage: build
  image: rust:1.80-bookworm
  extends: .install_dependencies
  script:
    - apt-get install -y gawk
    - ./build-aux/publish-crates-io.py
    - meson setup builddir
    - meson dist -C builddir
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "${TARBALL_ARTIFACT_PATH}"
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED

test-aarch64:
  image: rust:1.81-bookworm
  tags:
    - aarch64
  extends: .install_dependencies
  interruptible: true
  # As long as runners fail to start bwrap
  allow_failure: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu/
    - meson setup -Dbuildtype=debug -Dpython_tests=true -Dtest_skip_install=true --prefix=/usr builddir
    - meson install -C builddir
    - meson test -vC builddir
