.install_dependencies:
  before_script:
    - apt-get update
    - apt-get install -y bubblewrap

test-aarch64:
  image: rust:1.80-bookworm
  tags:
    - aarch64
  extends: .install_dependencies
  interruptible: true
  script:
    - bwrap --dev /dev --ro-bind /usr /usr --symlink /usr/lib64 /lib64 --symlink /usr/lib /lib ls
