variables:
  # Clone test-images
  GIT_SUBMODULE_STRATEGY: recursive

.install_dependencies:
  before_script:
    - apt update
    - apt install -y git curl meson pkg-config build-essential liblcms2-dev libgtk-4-dev libheif-dev gettext clang mold bubblewrap
    - git clone --depth 1 https://gitlab.freedesktop.org/cairo/cairo.git
    - meson setup cairo/builddir cairo
    - ninja install -C cairo/builddir
    - git clone --depth 1 https://gitlab.gnome.org/GNOME/gtk.git
    - meson setup -Dmedia-gstreamer=disabled -Dbuild-testsuite=false -Dbuild-examples=false -Dbuild-tests=false gtk/builddir gtk
    - ninja install -C gtk/builddir
  artifacts:
    when: always
    paths:
      - tests/failures
      - builddir/meson-logs
i386:
  image: rust@sha256:51f136e34f1cbb1837a7e1e5e6de581aa7a6a383a52606cd3248653beb11789e
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/i386-linux-gnu/
    - meson setup -Dprofile=dev builddir
    - meson install -C builddir
    - meson test -vC builddir

x86_64:
  image: rust:bookworm
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/
    - meson setup -Dprofile=dev builddir
    - meson install -C builddir
    - meson test -vC builddir