[workspace.package]
version = "0.0.1"
authors = ["Sophie Herold"]
description = "Sandboxed image rendering"
license = "LGPL-3.0-or-later"
homepage = "https://gitlab.gnome.org/GNOME/Incubator/loupe"
repository = "https://gitlab.gnome.org/GNOME/Incubator/loupe"
edition = "2021"
rust-version = "1.70"

[profile.release]
lto = true
codegen-units = 1

[profile.dev.package.image]
opt-level = 3

[workspace]
members = [
    "glycin",
    "glycin-utils",
    "loaders/glycin-image-rs",
    "loaders/glycin-heif",
]
default-members = [
    "glycin",
    "glycin-utils",
]
