[workspace.package]
version = "0.1.0-beta.2"
authors = ["Sophie Herold"]
description = "Sandboxed image rendering"
license = "LGPL-2.1"
homepage = "https://gitlab.gnome.org/sophie-h/glycin"
repository = "https://gitlab.gnome.org/sophie-h/glycin"
edition = "2021"
rust-version = "1.70"

[profile.release]
lto = true
codegen-units = 1

[profile.dev.package.image]
opt-level = 3

[workspace]
resolver = "2"
members = [
    "glycin",
    "glycin-utils",
    "loaders/glycin-image-rs",
    "loaders/glycin-heif",
    "loaders/glycin-jxl",
    "loaders/glycin-svg",
]
default-members = [
    "glycin",
    "glycin-utils",
]
