// Generated by gir (https://github.com/gtk-rs/gir @ 85fe8474df07)
// from  (@ c47f39197ea9+)
// from gir-files (@ b87d34dc3455)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GlyCicp", sizeof(GlyCicp), alignof(GlyCicp));
    printf("%s;%zu;%zu\n", "GlyCreatorClass", sizeof(GlyCreatorClass), alignof(GlyCreatorClass));
    printf("%s;%zu;%zu\n", "GlyEncodedImageClass", sizeof(GlyEncodedImageClass), alignof(GlyEncodedImageClass));
    printf("%s;%zu;%zu\n", "GlyFrameClass", sizeof(GlyFrameClass), alignof(GlyFrameClass));
    printf("%s;%zu;%zu\n", "GlyFrameRequestClass", sizeof(GlyFrameRequestClass), alignof(GlyFrameRequestClass));
    printf("%s;%zu;%zu\n", "GlyImageClass", sizeof(GlyImageClass), alignof(GlyImageClass));
    printf("%s;%zu;%zu\n", "GlyLoaderClass", sizeof(GlyLoaderClass), alignof(GlyLoaderClass));
    printf("%s;%zu;%zu\n", "GlyLoaderError", sizeof(GlyLoaderError), alignof(GlyLoaderError));
    printf("%s;%zu;%zu\n", "GlyMemoryFormat", sizeof(GlyMemoryFormat), alignof(GlyMemoryFormat));
    printf("%s;%zu;%zu\n", "GlyMemoryFormatSelection", sizeof(GlyMemoryFormatSelection), alignof(GlyMemoryFormatSelection));
    printf("%s;%zu;%zu\n", "GlyNewFrameClass", sizeof(GlyNewFrameClass), alignof(GlyNewFrameClass));
    printf("%s;%zu;%zu\n", "GlySandboxSelector", sizeof(GlySandboxSelector), alignof(GlySandboxSelector));
    return 0;
}
