[package]
name = "glycin"
readme = "../README.md"

version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
async-std = { version = "1.12.0", features = ["unstable"] }
futures = "0.3.28"
gdk = { package = "gdk4", version = "0.7.1", features = ["v4_12"] }
gio = "0.18.1"
glycin-utils = { version = "0.1.0-beta.2", path = "../glycin-utils/" }
lcms2 = { version = "6.0.0", git = "https://github.com/kornelski/rust-lcms2.git", rev = "579182f6acdf840b55b5e8bf66da3daa821d37ff" }
lcms2-sys = { git = "https://github.com/kornelski/rust-lcms2.git", rev = "579182f6acdf840b55b5e8bf66da3daa821d37ff" }
memfd = "0.6.3"
memmap = { package = "memmap2", version = "0.7.0" }
nix = "0.26.2"
rgb = "0.8.36"
safe-transmute = "0.11.2"
zbus = "3.13.1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
features = []
