# This config name has a 0- prefix to be preferred over the glycin-image config.
# The glycin-image config does not support quality (lossy encoding).

[editor:image/webp]
Exec = @EXEC@
Identifiers=0:RIFF,8:WEBP;
Extension=webp
Creator = true
CreatorEncodingQuality = true
CreatorMemoryFormats=R8g8b8;R8g8b8a8
