// Generated by gir (https://github.com/gtk-rs/gir @ 85fe8474df07)
// from  (@ 028df45546c3+)
// from gir-files (@ b87d34dc3455)
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
#![allow(
    clippy::approx_constant,
    clippy::type_complexity,
    clippy::unreadable_literal,
    clippy::upper_case_acronyms
)]
#![cfg_attr(docsrs, feature(doc_cfg))]

#[allow(unused_imports)]
use std::ffi::{
    c_char, c_double, c_float, c_int, c_long, c_short, c_uchar, c_uint, c_ulong, c_ushort, c_void,
};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};
#[cfg(unix)]
#[allow(unused_imports)]
use libc::{dev_t, gid_t, pid_t, socklen_t, uid_t};
#[allow(unused_imports)]
use libc::{intptr_t, off_t, size_t, ssize_t, time_t, uintptr_t, FILE};
use {gdk_sys as gdk, glib_sys as glib, gly_sys as gly};

extern "C" {

    //=========================================================================
    // Other functions
    //=========================================================================
    pub fn gly_gtk_frame_get_texture(frame: *mut gly::GlyFrame) -> *mut gdk::GdkTexture;

}
